### ISSUE TITLE
Клановые войны. Законопроекты.

### ISSUE THREAD

**Issue by Bananarhist** [cofob/buldzhat_rules#1]
Все законопроекты от Bananarhist по НЕ душным правилам КВ

**Comment by cofob** [comment]
Можешь все свои предложения в предложки оформить в Pull Request?

**Comment by cofob** [comment]
Я просто не понимаю как их организовать.

**Comment by Bananarhist** [comment]
Полный законопроект клановых войн по Бананархисту:

1. ОПРЕДЕЛЕНИЯ

Война - особый вид отношения между кланами, предпологающий разрешение на уничтожение построек, убийство членов и воровство ресурсов одного клана другим кланом.

Клан - группа из 5 и более игроков, зарегистрированная администрацией.

База - как минимум одно здание, построенное/занятое кланом или отдельными его участниками. Обязательно наличие как минимум одной кровати.

Активная база - субъективное понятие, требует доработки

2. ПРАВИЛА КЛАНОВЫХ ВОЙН

а) В войнах учавствуют только кланы, вмешательство третьих лиц карается администрацией

б) Кланы объявляют войны когда посчитают нужным без каких либо ограничений

в) Администрация не имеет права вмешательства в отношения между кланами. Каждый клан сам выстраивает отношения с остальными

г) Клан может объявить нейтралитет в конкретном конфликте, но соблюдение этого нейтралитета полностью на совести этого и других кланов

д) В случае боевых столкновений на терриории общественных пространств (спавн, хаб в аду, магистрали) или на территории третьих лиц запрещается разрушение зданий и прочее гриферство

3. ЗАКЛЮЧЕНИЕ
Дорогая администрация, не надо душить, просто не надо, анальная модерация это НЕ весело

**Comment by cofob** [comment]
Сделал, проверяй. #2

**Comment by Saiv46** [comment]
@cofob Закрывай issue
